### ISSUE TITLE
我项目下执行了Clean Project然后出现了如下提示,需要做什么处理么

### ISSUE THREAD

**Issue by sweet2o09** [Flywith24/VersionControlDemo#1]
Project directory 'D:\demo\VersionControlDemo-master\version' is not part of the build defined by settings file 'D:\demo\VersionControlDemo-master\settings.gradle'. If this is an unrelated build, it must have its own settings file.

**Comment by Flywith24** [comment]
理论上是不影响对

不过想要处理也好办，在 version module 中加入一个空的 settings.gradle 即可

pull 一下新代码

**Comment by Flywith24** [comment]
> Project directory 'D:\demo\VersionControlDemo-master\version' is not part of the build defined by settings file 'D:\demo\VersionControlDemo-master\settings.gradle'. If this is an unrelated build, it must have its own settings file.

理论上是不影响的

不过想要处理也好办，在 version module 中加入一个空的 settings.gradle 即可

pull 一下新代码
